#!/bin/bash
#PBS -N qdpt.4 
#PBS -o qdout.04.log
#PBS -e qderr.04.log
#PBS -l select=1:ncpus=32:mem=60gb
#PBS -l walltime=45:00:00
#PBS -q clx
cd $PBS_O_WORKDIR
cd ..
PYTHON=/home/g.samarth/.conda/envs/jaxpyro/bin/python
SCRIPT=/home/g.samarth/qdpy-numpyro/qdpy_jax/run_reduced_problem_model.py
OUTFILE=/home/g.samarth/qdpy-numpyro/jobscripts/qd4out.log
ERRFILE=/home/g.samarth/qdpy-numpyro/jobscripts/qd4err.log
$PYTHON $SCRIPT  --maxiter 150 --chain_num 4 >$OUTFILE  2>$ERRFILE
